version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    versioning-strategy: lockfile-only
    groups:
      minor_version:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
